
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: low-end-operator
  namespace: low-end-ctrl
rules:
- apiGroups: ["fractal-cluster.eu"]
  resources: ["lowends"]
  verbs: ["*"]
- apiGroups: [""]
  resources: [events]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["GET", "LIST"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: low-end-operator
  namespace: low-end-ctrl 
subjects:
- kind: ServiceAccount
  name: low-end-operator
  namespace: low-end-ctrl
roleRef:
  kind: ClusterRole
  name: low-end-operator
  apiGroup: rbac.authorization.k8s.io